geraldgsh/new-york-times-clone

index.html, style.css
- Positioning navbar elements.
- Styled right corner buttons.
=> Styling navbar

index.html, style.css
- Add the main title box.
- Inside the box put the title and styled it.
=> Add the main title box and text.

index.html, style.css
=> Redo the project begin doing layout

stickler.yml
=> add stickler file

index.html, style.css
=> navbar layout

index.html, style.css
=> Add the main-info section

index.html, style.css
- header left box positioning.
- added elements (icons) (buttons).
=> header positioning 1

index.html, style.css
- positioned main img box..
- positionied main title box.
=> positioning header elements

index.html, style.css
- resize and re-position image
- added caption
=> figure caption

index.html, style.css
- Info 1 section boxes positioned.
=> Implemented info-1-boxes

style.css
=> float-boxes

index.html, style.css
Already positioned sections:
- main header
- tex-section
- pre-footer section
-footer section
=> Positioning box

index.html, style.css
Implemented navbar on flexbox.
Positioned elements.
added comments for info.
=> Navbar in flex box

style.css
- revert to using positions and floats
=> navbar-rework

index.html, style.css
navbar items positioned.
main container placed.
=> navbar positioned items

index.html, style.css
=> header-title-1

index.html, style.css
- Positioned main section.
- Positioned elemens main section.
=> Added the elemens of main section

style.css
- Navbar elements positioned using floats.
- Navbar elements styled.
- Only change background color the base color.
=> Navbar done only change back colors

index.html, style.css
- added header 1 section and elements
=> added-header-1

index.html, style.css
=> article-elements

index.html, style.css
- Add editor pick section box.
- Already placed father box.
=>  added editor pick

index.html, style.css
header 2 conteienr implemented
=> header 2 container and items implemented

index.html, style.css
=> added-art2

index.html, style.css
- added columns for news content preview
=> morespace column
